### ISSUE TITLE
About load images

### ISSUE THREAD

**Issue by ecastillot** [c4s4/mdtools#1]
Is it difficult to implement this syntax for load images?

```<p align="center"><img src="images/sgc_logo.png" width="400"/></p>```

Regards

**Comment by c4s4** [comment]
I suppose that you want to insert a centered image with a width of 400 pixels. I would:

- Resize the image to 400 pixels width
- Write in the document `![](images/sgc_logo.png)`

This should probably do what you want.

**Comment by c4s4** [comment]
Is this OK for you, can I close the issue ?

**Comment by ecastillot** [comment]
Thanks a lot!

However, with your syntax can't be align to center, but it's ok.

**Comment by c4s4** [comment]
Yes it is centered by default. With the sample markdown file in *test* directory, the image is included with `![Image title](casa.png)` and resulting PDF file looks like :

![example](https://user-images.githubusercontent.com/1253887/92306336-9c021c80-ef8e-11ea-9ec3-cf8d6b90c237.png)

Thus I close the issue.
